//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMallCatalog.Models.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Goods()
        {
            this.OrderDetails = new HashSet<OrderDetails>();
        }
    
        public string g_ID { get; set; }
        public string g_Name { get; set; }
        public string t_ID { get; set; }
        public double g_Price { get; set; }
        public double g_Discount { get; set; }
        public short g_Number { get; set; }
        public System.DateTime g_ProduceDate { get; set; }
        public string g_Image { get; set; }
        public string g_Status { get; set; }
        public string g_Description { get; set; }
    
        public virtual Types Types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
    }
}
