//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMallCatalog.Models.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetails
    {
        public int d_ID { get; set; }
        public string o_ID { get; set; }
        public string g_ID { get; set; }
        public double d_Price { get; set; }
        public short d_Number { get; set; }
    
        public virtual Goods Goods { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
